"""
Django settings for WebSongHong project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*6)yyubt#qy3r9g4e%)8(*ch$c&4=(-woc!6!1c*(504qs=ct'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '192.168.1.118', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

JAZZMIN_SETTINGS = {
    # Tiêu đề & thương hiệu
    "site_title": "Keo Vữa Sông Hồng",
    "site_header": "SHK Mortar Admin",
    "site_brand": "SHK MORTAR",
    "welcome_sign": "Chào mừng đến trang quản trị Keo Vữa Sông Hồng",
    "copyright": "© 2025 Công ty TNHH Keo Vữa Sông Hồng",

    # Logo (để trống nếu chưa có, dùng text)
    "site_logo": None,
    "site_icon": None,
    "site_logo_classes": "img-circle",

    # Tìm kiếm
    "search_model": ["main.Product", "main.News", "main.Distributor"],

    # User avatar
    "user_avatar": None,

    # Top menu
    "topmenu_links": [
        {"name": "Trang chủ web", "url": "/", "new_window": True, "icon": "fas fa-globe"},
        {"name": "Sản phẩm", "url": "/san-pham/", "new_window": True, "icon": "fas fa-box"},
    ],

    # Menu trái (sidebar) — chia theo nhóm
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": [
        "main.Product",
        "main.ProductCategory",
        "main.Project",
        "main.ConsultationRequest",
        "main.Catalogue",
        "main.News",
        "main.NewsCategory",
        "main.Banner",
        "main.Distributor",
        "main.DealerRegistration",
        "main.ContactMessage",
        "auth",
    ],

    "icons": {
        "auth":                         "fas fa-users-cog",
        "auth.user":                    "fas fa-user",
        "auth.Group":                   "fas fa-users",
        "main.Product":                 "fas fa-box-open",
        "main.ProductCategory":         "fas fa-tags",
        "main.Project":                 "fas fa-hard-hat",
        "main.ConsultationRequest":     "fas fa-comments",
        "main.Catalogue":               "fas fa-file-pdf",
        "main.News":                    "fas fa-newspaper",
        "main.NewsCategory":            "fas fa-folder",
        "main.Banner":                  "fas fa-image",
        "main.Distributor":             "fas fa-store",
        "main.DealerRegistration":      "fas fa-handshake",
        "main.ContactMessage":          "fas fa-envelope",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Custom sidebar links
    "custom_links": {
        "main": [{
            "name": "Xem website",
            "url": "/",
            "icon": "fas fa-external-link-alt",
            "new_window": True,
        }]
    },

    # Related modal
    "related_modal_active": True,

    # UI config
    "custom_css": "css/admin_custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },

    # Language
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WebSongHong.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebSongHong.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
