# Generated by Django 6.0.5 on 2026-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=300, verbose_name='Công ty / Dự án')),
                ('interest', models.CharField(blank=True, max_length=200, verbose_name='Quan tâm đến')),
                ('message', models.TextField(blank=True, verbose_name='Yêu cầu cụ thể')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Đã xử lý')),
            ],
            options={
                'verbose_name': 'Đăng ký tư vấn',
                'verbose_name_plural': 'Đăng ký tư vấn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Tên dự án')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('category', models.CharField(choices=[('dan-dung', 'Dự án dân dụng'), ('cong-nghiep', 'Dự án công nghiệp / thương mại')], default='dan-dung', max_length=20, verbose_name='Loại dự án')),
                ('client', models.CharField(blank=True, max_length=300, verbose_name='Chủ đầu tư')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Địa điểm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả dự án')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Dự án nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_used', models.ManyToManyField(blank=True, to='main.product', verbose_name='Sản phẩm sử dụng')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
