# Generated by Django 6.0.5 on 2026-08-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consultationrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='main.news', verbose_name='Bài viết liên quan'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_news', to='main.product', verbose_name='Sản phẩm liên quan'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_news', to='main.project', verbose_name='Dự án liên quan'),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Tiêu đề catalogue')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('category', models.CharField(choices=[('san-pham', 'Catalogue sản phẩm'), ('giai-phap', 'Catalogue giải pháp'), ('du-an', 'Catalogue dự án')], default='san-pham', max_length=20, verbose_name='Loại catalogue')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='catalogues/', verbose_name='Ảnh bìa')),
                ('file', models.FileField(blank=True, null=True, upload_to='catalogues/files/', verbose_name='File PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_catalogues', to='main.product', verbose_name='Sản phẩm liên quan')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='related_catalogues', to='main.project', verbose_name='Dự án liên quan')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogue',
                'ordering': ['category', 'title'],
            },
        ),
    ]
