# Generated by Django 6.0.5 on 2026-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_related_articles_news_related_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, help_text='Dán link YouTube video phóng sự', null=True, verbose_name='URL YouTube'),
        ),
    ]
