# Generated by Django 6.1 on 2026-09-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_image_2_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('cong-nghiep', 'Dự án công nghiệp / thương mại'), ('dan-dung', 'Dự án dân dụng')], default='dan-dung', max_length=20, verbose_name='Loại dự án'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order_id', models.CharField(blank=True, max_length=50, verbose_name='Mã đơn tùy chỉnh')),
                ('source', models.CharField(choices=[('direct', 'Tại cửa hàng'), ('facebook', 'Facebook'), ('zalo', 'Zalo'), ('website', 'Website'), ('other', 'Khác')], default='direct', max_length=20, verbose_name='Nguồn đơn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('branch', models.CharField(default='Cửa hàng chính', max_length=200, verbose_name='Bán tại chi nhánh')),
                ('staff', models.CharField(default='Admin', max_length=200, verbose_name='Nhân viên phụ trách')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày hẹn giao')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Tags')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền hàng')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí giao hàng')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thành tiền')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn giá')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
