# Generated by Django 6.1 on 2026-09-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_alter_project_category_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['order', 'category', 'title'], 'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalog'},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên nhóm tài liệu (VD: Tài liệu keo dán gạch)'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Số thứ tự sắp xếp'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='category',
            field=models.CharField(choices=[('san-pham', 'Catalog sản phẩm'), ('giai-phap', 'Catalog giải pháp'), ('du-an', 'Catalog dự án')], default='san-pham', max_length=20, verbose_name='Loại catalog'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Tiêu đề catalog'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('dan-dung', 'Dự án dân dụng'), ('cong-nghiep', 'Dự án công nghiệp / thương mại')], default='dan-dung', max_length=20, verbose_name='Loại dự án'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
