# Generated by Django 6.1 on 2026-09-04 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_author_news_updated_at_alter_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.CharField(default='Công ty TNHH Keo Vữa Sông Hồng', max_length=200, verbose_name='Tác giả'),
        ),
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
