# Generated by Django 6.1 on 2026-09-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_author_project_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='theme/', verbose_name='Logo công ty')),
                ('header_text', models.TextField(blank=True, verbose_name='Text đầu trang')),
                ('show_megamenu', models.BooleanField(default=True, verbose_name='Hiển thị megamenu')),
            ],
            options={
                'verbose_name': 'Giao diện',
                'verbose_name_plural': 'Giao diện',
            },
        ),
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['order', 'category', 'title'], 'verbose_name': 'Catalogue', 'verbose_name_plural': 'Catalogue'},
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='category',
            field=models.CharField(choices=[('san-pham', 'Catalogue sản phẩm'), ('giai-phap', 'Catalogue giải pháp'), ('du-an', 'Catalogue dự án')], default='san-pham', max_length=20, verbose_name='Loại catalogue'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Tiêu đề catalogue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh 2'),
        ),
    ]
