# Generated by Django 6.1 on 2026-09-07 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_themesettings_alter_catalogue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Catalogue', 'verbose_name_plural': 'Catalogue'},
        ),
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Cài đặt Giao diện', 'verbose_name_plural': 'Cài đặt Giao diện'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.AddField(
            model_name='themesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link Facebook'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SĐT footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Link YouTube (Footer)'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_zalo',
            field=models.URLField(blank=True, null=True, verbose_name='Link Zalo'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hotline_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hotline 1'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hotline_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hotline 2'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='intro_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả giới thiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='intro_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề giới thiệu'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='intro_youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link YouTube'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='open_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giờ mở cửa'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='show_intro',
            field=models.BooleanField(default=True, verbose_name='Hiển thị Module Giới thiệu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text đầu trang'),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='show_megamenu',
            field=models.BooleanField(default=False, verbose_name='Hiển thị megamenu'),
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh banner')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link liên kết')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.themesettings')),
            ],
            options={
                'verbose_name': 'Banner Trang chủ',
                'verbose_name_plural': 'Banners Trang chủ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Logo đối tác')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đối tác')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link liên kết')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='main.themesettings')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'ordering': ['order'],
            },
        ),
    ]
