# Generated by Django 6.1 on 2026-09-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_catalogue_options_alter_themesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerregistration',
            name='products_distributed',
            field=models.TextField(blank=True, null=True, verbose_name='Sản phẩm phân phối'),
        ),
        migrations.AddField(
            model_name='dealerregistration',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ trụ sở'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='company',
            field=models.CharField(max_length=300, verbose_name='Tên doanh nghiệp/Hộ Kinh Doanh'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='dealerregistration',
            name='province',
            field=models.CharField(max_length=100, verbose_name='Khu vực đăng ký đại lý'),
        ),
    ]
