# Generated by Django 6.1 on 2026-09-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_dealerregistration_products_distributed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-is_featured', 'name'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã SKU'),
        ),
    ]
