# Generated by Django 6.1 on 2026-09-08 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_options_product_order_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='products/certificates/', verbose_name='Chứng chỉ chất lượng (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ecatalog_file',
            field=models.FileField(blank=True, null=True, upload_to='products/ecatalog/', verbose_name='File E-catalog (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_norms',
            field=models.TextField(blank=True, verbose_name='Định mức sử dụng'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link video YouTube'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Hướng dẫn thi công'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Đoạn giới thiệu tổng quan'),
        ),
        migrations.CreateModel(
            name='ProductHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Ý nổi bật')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='main.product')),
            ],
            options={
                'verbose_name': 'Ưu điểm vượt trội',
                'verbose_name_plural': 'Ưu điểm vượt trội',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.product')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Tên thông số')),
                ('value', models.CharField(max_length=300, verbose_name='Giá trị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='main.product')),
            ],
            options={
                'verbose_name': 'Thông số sản phẩm',
                'verbose_name_plural': 'Thông số sản phẩm',
                'ordering': ['order'],
            },
        ),
    ]
