# Generated by Django 6.1 on 2026-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_certificate_file_product_ecatalog_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Thứ tự'),
        ),
    ]
