# Generated by Django 6.1 on 2026-09-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_producthighlight_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Ảnh/Video sản phẩm', 'verbose_name_plural': 'Ảnh/Video sản phẩm'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh (URL ngoài)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Ảnh'), ('video', 'Video')], default='image', max_length=10, verbose_name='Loại'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video (URL YouTube)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Ảnh (tải lên)'),
        ),
    ]
