# Generated by Django 6.1 on 2026-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_productimage_options_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Catalogue', 'verbose_name_plural': 'Catalogue'},
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Thông tin sản phẩm'),
        ),
    ]
