# Generated by Django 6.1 on 2026-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_projectcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', '-published_at'], 'verbose_name': 'Tin tức', 'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-is_featured', '-created_at'], 'verbose_name': 'Dự án', 'verbose_name_plural': 'Dự án'},
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
